name: 배포
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run scripts in server
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ~/web-fleamarket-9
            sudo git fetch origin main
            sudo git reset --hard origin/main
            cd client
            sudo npm install
            sudo npm run build
            cd ../server
            sudo npm install
            sudo npm run build
            sudo pm2 restart all
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
